### ISSUE TITLE
You could maybe move to use extend-publish

### ISSUE THREAD

**Issue by mitar** [lamhieu-vk/unblock#2]
I made it some time ago as replacement for MeteorX. It tries to be more maintained: https://github.com/peerlibrary/meteor-extend-publish

But I am not sure if it provides everything one needs to implement this package.

**Comment by lh0x00** [comment]
To handle unblock for `Meteor.publish` we need to expose and override some `Session.prototype ` and `Subscription.prototype` from Meteor, exposed by MeteorX.

**Comment by mitar** [comment]
I see.

**Comment by lh0x00** [comment]
@mitar Thanks for your suggestion!
